name: Ler Inscricao e Criar Arquivo
on:
  issues:
    types: [opened]
jobs:
  criar:
    if: contains(github.event.issue.labels.*.name, 'inscricao')
    runs-on: ubuntu-latest
    permissions: { contents: write, issues: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: node.github/scripts/criar_de_issue.js '${{ github.event.issue.body }}'
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sections/ktp/projetotransformacao/projetos/2026/
          git commit -m "Add aluno da issue #${{ github.event.issue.number }}" || exit 0
          git push
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.close({
              owner: context.repo.owner,
              repo: context.repo,
              issue_number: context.issue.number
            })
