name: ia.yml - fixed ignora k-onversa
on:
  push:
    paths-ignore:
      - "korvil/sok/k-or/k-onversa/**"
  pull_request:
    paths-ignore:
      - "korvil/sok/k-or/k-onversa/**"
jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ignorado k-onversa - anti-duplicação"
